# Generated by Django 4.2.30 on 2026-07-14 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_alter_estimate_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('awaiting', 'Awaiting'), ('completed', 'Completed'), ('stopping', 'Stopping'), ('stopped', 'Stopped'), ('failed', 'Failed'), ('stale', 'Stale')], default='created', max_length=30)),
                ('type', models.CharField(choices=[('comment_thread', 'Comment Thread'), ('assignment', 'Assignment')], default='comment_thread', max_length=30)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('external_link', models.URLField(blank=True, max_length=1024, null=True)),
                ('error_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Agent Run',
                'verbose_name_plural': 'Agent Runs',
                'db_table': 'agent_runs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='agent_slug',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='agent_run',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AgentRunActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('prompt', 'Prompt'), ('thought', 'Thought'), ('action', 'Action'), ('response', 'Response'), ('elicitation', 'Elicitation'), ('error', 'Error')], max_length=30)),
                ('content', models.JSONField(default=dict)),
                ('content_metadata', models.JSONField(blank=True, default=dict)),
                ('ephemeral', models.BooleanField(default=False)),
                ('signal', models.CharField(choices=[('auth_request', 'Auth Request'), ('continue', 'Continue'), ('select', 'Select'), ('stop', 'Stop')], default='continue', max_length=30)),
                ('signal_metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_run_activities', to=settings.AUTH_USER_MODEL)),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='db.agentrun')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_run_activities', to='db.issuecomment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Agent Run Activity',
                'verbose_name_plural': 'Agent Run Activities',
                'db_table': 'agent_run_activities',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='agentrun',
            name='agent_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='db.issuecomment'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='db.issue'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='source_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_agent_runs', to='db.issuecomment'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='stopped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stopped_agent_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
    ]
